### ISSUE TITLE
...

### ISSUE THREAD

**Issue by Kiri7** [Kiri7/Test#1]
What is this

**Comment by Kiri7** [comment]
fadfhdsh;FG
\

**Comment by Kiri7** [comment]
._.

**Comment by Leo1611** [comment]
this is random

**Comment by Kiri7** [comment]
Ikr

**Comment by Leo1611** [comment]
i can lol

**Comment by Kiri7** [comment]
Great

**Comment by Kiri7** [comment]
Still no idea what this is

**Comment by Leo1611** [comment]
so ? lol 
can we use this for anything ? lol

**Comment by Kiri7** [comment]
I guess

**Comment by Leo1611** [comment]
lol

**Comment by Kiri7** [comment]
Great uselessness

**Comment by Leo1611** [comment]
ikr lol

**Comment by Kiri7** [comment]
We are not gonna use this are we

**Comment by Kiri7** [comment]
Better not btw

**Comment by Leo1611** [comment]
hmm actually this website is for programming lol

**Comment by Kiri7** [comment]
Ik

**Comment by Kiri7** [comment]
I made this on a whim

**Comment by Leo1611** [comment]
lol

**Comment by Kiri7** [comment]
Guess Kirbex

**Comment by Kiri7** [comment]
Random desu

**Comment by Leo1611** [comment]
![its-useless](https://user-images.githubusercontent.com/34199362/33521084-2acafa90-d7c8-11e7-8900-6e172fdc5ad7.jpg)

**Comment by Kiri7** [comment]
Yup

**Comment by Leo1611** [comment]
lol

**Comment by Kiri7** [comment]
Now Imma delete all this

**Comment by Kiri7** [comment]
Okay?

**Comment by Leo1611** [comment]
okay? lol

**Comment by Kiri7** [comment]
What?

**Comment by Leo1611** [comment]
will miss you useless chat

**Comment by Kiri7** [comment]
Yes we will

**Comment by Leo1611** [comment]
kirbex

**Comment by Kiri7** [comment]
(not)

**Comment by Leo1611** [comment]
![hqdefault](https://user-images.githubusercontent.com/34199362/33521095-5d73c710-d7c8-11e7-9632-a0f613a34e82.jpg)

**Comment by Kiri7** [comment]
Lol

**Comment by Kiri7** [comment]
Agreed

**Comment by Leo1611** [comment]
he can't see lol

**Comment by Leo1611** [comment]
agreed too !

**Comment by Kiri7** [comment]
Ik but still

**Comment by Leo1611** [comment]
we can talk abt ppl they won't understand

**Comment by Kiri7** [comment]
Did the pfp thingy change?

**Comment by Leo1611** [comment]
hmm H ?

**Comment by Kiri7** [comment]
It did change here but not on discord

**Comment by Leo1611** [comment]
noooo

**Comment by Leo1611** [comment]
rip lol

**Comment by Leo1611** [comment]
haha so useless to close it

**Comment by Kiri7** [comment]
You can still type lol

**Comment by Leo1611** [comment]
wow you are rude

**Comment by Leo1611** [comment]
what did you say on kirbex *wink wink*

**Comment by Leo1611** [comment]
ooooo

**Comment by Leo1611** [comment]
what srsly ? rude

**Comment by Leo1611** [comment]
kirbex is like this ?

**Comment by Leo1611** [comment]
i didn't knew *wink*

**Comment by Leo1611** [comment]
yes

**Comment by Leo1611** [comment]
where ?

**Comment by Kiri7** [comment]
._.

**Comment by Kiri7** [comment]
Try again Leo
